server:
  port: 8080
  error:
    include-message: always
  services:
    driver:
      port: 8083
      #      host: localhost
      host: driver
    car:
      port: 8082
      #      host: localhost
      host: car
    race:
      port: 8081
      #      host: localhost
      host: race
    component:
      port: 8084
      #      host: localhost
      host: component
    authentication:
      port: 8080
      #      host: localhost
      host: authentication

formula:
  authenticate:
    api-key: "1372dbdf7f17e6b6bee8221fa4485d881e5ba1a59884dffe3679f4284353c5d9"

springdoc:
  api-docs:
    path: /openapi
  swagger-ui:
    path: /swagger-ui.html

spring:
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:file:./src/main/resources/data/authentication;MODE=PostgreSQL
    driverClassName: org.h2.Driver
    username: admin
    password: admin
  security:
    oauth2:
      client:
        registration:
          muni:
            client-id: 7e02a0a9-446a-412d-ad2b-90add47b0fdd
            client-secret: 48a2b2e3-4b2b-471e-b7b7-b81a85b6eeef22f347f2-3fc9-4e16-8698-3e2492701a89
            client-name: "MUNI Unified Login"
            provider: muni
            scope:
              - openid
              - profile
              - email
              - test_1
              - test_2
              - test_3
              - test_4
        provider:
          muni:
            issuer-uri: https://oidc.muni.cz/oidc/