{
 "title": "Main Formula One Dashboard",
 "description": "The Formula 1 Metrics Dashboard is a powerful monitoring and analytics tool designed specifically for the Formula 1 racing domain. It provides comprehensive insights and visualizations of key performance metrics and data related to Formula 1 races, cars, drivers, and components.",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Overall statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{instance=\"race:8081\"}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 17, "x": 7, "y": 1 },
   "targets": [
    { "expr": "system_cpu_usage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{instance=\"race:8081\"} * 1000"
    }
   ]
  },
  { "title": "Indivitual Microservices", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Availability",
   "type": "stat",
   "gridPos": { "h": 24, "w": 5, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"driver:8083\"}",
     "legendFormat": "Driver"
    },
    {
     "expr": "up{instance=\"component:8084\"}",
     "legendFormat": "Component"
    },
    {
     "expr": "up{instance=\"race:8081\"}",
     "legendFormat": "Race"
    },
    {
     "expr": "up{instance=\"car:8082\"}",
     "legendFormat": "Car"
    }
   ]
  },
  {
   "title": "Driver requests counter by status (in seconds)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 5, "y": 11 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{instance=\"driver:8083\"}[$__rate_interval])) by (status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Driver request errors (in seconds)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 11 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{instance=\"driver:8083\"}[$__rate_interval])) by (error)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Component requests counter by status (in seconds)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 5, "y": 17 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{instance=\"component:8084\"}[$__rate_interval])) by (status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Component request errors (in seconds)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 17 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{instance=\"component:8084\"}[$__rate_interval])) by (error)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Race requests counter by status (in seconds)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 5, "y": 23 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{instance=\"race:8081\"}[$__rate_interval])) by (status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Race request errors (in seconds)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 23 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{instance=\"race:8081\"}[$__rate_interval])) by (error)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Car requests counter by status (in seconds)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 5, "y": 29 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{instance=\"car:8082\"}[$__rate_interval])) by (status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Car request errors (in seconds)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 29 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{instance=\"car:8082\"}[$__rate_interval])) by (error)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}