server:
  port: 8081
  error:
    include-message: always
  services:
    driver:
      port: 8083
      #      host: localhost
      host: driver
    car:
      port: 8082
      #      host: localhost
      host: car
    race:
      port: 8081
      #      host: localhost
      host: race
    component:
      port: 8084
      #      host: localhost
      host: component
    authentication:
      port: 8080
      #      host: localhost
      host: authentication

formula:
  authenticate:
    api-key: "1372dbdf7f17e6b6bee8221fa4485d881e5ba1a59884dffe3679f4284353c5d9"

springdoc:
  api-docs:
    path: /raceApi
  swagger-ui:
    path: /swagger-ui.html

spring:
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:file:./src/main/resources/data/race;MODE=PostgreSQL
    driverClassName: org.h2.Driver
    username: admin
    password: admin
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: [ "health","prometheus", "metrics" ]
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true